version: '3'

services:
  db:
    image: mysql:latest
    volumes:
      - ./static/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: mysql_test
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"