// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type EditTodo struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewTodo struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}
